# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SuperNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SuperNews
  pod 'Alamofire'
  pod 'Kingfisher'

  target 'SuperNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SuperNewsUITests' do
    # Pods for testing
  end

end
